### PR TITLE
Update NodeJs Document.md

### PR DESCRIPTION
**Pull request by sovetw**
I made language and formatting updates to the NodeJs Document.md file. You haven't asked for it, but I reviewed it while looking at other contents in your repository. Please review the edits for technical accuracy.

### CODE REVIEW

**Comment by pareek-narendra** [comment]
@sovetw 
Better
Can you add a bit more information about the code and functions used if you are familiar with node js.

**Comment by sovetw** [comment]
Thanks. I will try to add more information once I edit the document for Go Lang.

**Comment by sovetw** [comment]
Hi, I made two more commits today, one to the NodeJs document.md for a minor typo, and another to the Golang document.md (added instructions). Do I need to create a new pull request? When I try to create a new pull request, I see this comments page with my yesterday's pull request which has not been merged in your branch yet.

I am learning GitHub; so apologies if this is not the right process.

**Comment by pareek-narendra** [comment]
@sovetw 
Good work! Thanks for contributing.

You can raise multiple pull requests but need to change your base branch then only it is possible.
For now, you are raising a PR from `sovetw:master` to `pareek-narendra:master` so what you can do in future,
create a branch from you forked repo's master branch
commit your code to that branch
push the changes
raise the PR from that branch

**Review by pareek-narendra — APPROVED** [review]

**Comment by pareek-narendra** [comment]
@sovetw 
You can do one more contribution by adding the golang Document.md reference in the main readme.md file.
Please check NodeJs reference link is already there in the readme file.
Your existing PR has been merged so you can create a new PR now.
Keep contributing :)

**Pull request merged**
